import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <nav style={{
          display: "flex",
          gap: "20px",
          padding: "16px 40px",
          background: "#111",
        }}>
          <Link href="/dashboard" style={{ color: "white" }}>
            Dashboard
          </Link>
          <Link href="/trade" style={{ color: "white" }}>
            Trade
          </Link>
        </nav>
        {children}
      
      </body>
    </html>
  );
}
